version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: wallet-audit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis Commander for web-based Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: wallet-audit-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: wallet-audit-network 